#----------------
# For testing
#----------------
version: '3.8'

services:
  db:
    image: mysql:5.7.31
    container_name: db
    hostname: db
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=production
      - MYSQL_USER=production
      - MYSQL_PASSWORD=production
      - MYSQL_TCP_PORT=3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  api:
    depends_on:
      - db
    env_file:
      - api.env # env of Bucket and Mailgun
    build:
      context: ./enqueter-api
      dockerfile: ./Dockerfile
      args:
        SECRET_KEY: "hogehogehoge"
        FRONT_URL: "http://localhost:3000"
        SQLALCHEMY_DATABASE_URI: "mysql+pymysql://production:production@db/production?charset=utf8mb4"
    volumes:
      - socket:/tmp

  web:
    build: ./enqueter-web
    ports:
      - "80:80"
    volumes:
      - socket:/tmp

volumes:
  socket:

